### ISSUE TITLE
All badges show 0

### ISSUE THREAD

**Issue by martin-t** [XAMPPRocky/tokei_rs#123] opened 2021-12-04 14:11 UTC
Not sure when this started (at least yesterday) but it seems that all badges on all projects using tokei.rs show 0 lines of code. It can be seen for example in tokei's own readme.

**Comment by martin-t** [comment] 2021-12-11 19:31
Seems to be fixed now, closing. Thanks in case you did anything ;)

**Comment by XAMPPRocky** [comment] 2021-12-11 19:52
Thank you for your issue! Yeah, it's a bug where the server was out of disk space, restarting and adding a cleanup task fixed it.

**Comment by martin-t** [comment] 2022-02-08 21:28
Looks like the issue has returned, no idea if the cause is the same.

**Comment by miraclx** [comment] 2022-06-23 04:34
Just bumping here because this Issue has returned again.

**Comment by XAMPPRocky** [comment] 2022-06-23 06:09
@baseplate-admin There's a lot I could do, but the amount of time I can spend working on it at the moment is very limited as I have a full-time job and other obligations for other projects. If you'd like me to spend more time on this project, [sponsoring me on GitHub](https://github.com/sponsors/XAMPPRocky) directly affects the amount of time I can spend on projects like tokei.rs.

---

@miraclx Fixed now, thank you.

**Comment by Khadeeejah** [comment] 2022-08-09 13:38
Hi @XAMPPRocky, thanks for building this.

I just ran into this issue and I'm not sure the cleanup script is working yet. Could you take a look?

**Comment by XAMPPRocky** [comment] 2022-08-09 13:56
@Khadeeejah I'll give it a kick, but to clarify for people in the thread it's not a cleanup script issue. The issue is that some people are requesting repositories than are larger than the total disk space of the server. I'm not storing things in object storage as that's very expensive and requires decent effort to ensure that the bill doesn't scale out of control. I do have some much larger fixed sized storage that I'm moving tokei.rs too, but again I haven't had the time to debug all the issues with the new server setup yet.

**Comment by XAMPPRocky** [comment] 2023-02-27 07:55
@JordanWelsman Thank you for your question, unfortunately I've not had any time to spend on tokei.rs, so the status of that hasn't changed. I will restart the server when the issue is noticed.

**Comment by JordanWelsman** [comment] 2023-03-03 14:58
@XAMPPRocky The issue seems to be fixed, at least on my repositories. Need more people to confirm. Thanks!

**Comment by AlbertUnruh** [comment] 2023-03-23 21:07
Don't know whether it was working in the meantime, but in all my repos the line-count is at `0` and in about 20% everything else is at `0` as well *(but this may be due to the inactivity of the repos)*.

**Comment by JordanWelsman** [comment] 2023-04-03 03:36
Yep, back to showing zero for my repos too.

**Comment by Trolldemorted** [comment] 2023-07-06 20:23
is it gone for good now? Are there any alternatives?

**Comment by aschey** [comment] 2023-07-16 16:43
I made a version of this that runs as a Vercel serverless function so that it can be more resilient against large requests that take down the service. Since it's serverless, it'll just spin up a new container if the current one dies. You can use the link I provide in the repo or fork it and host it on your own Vercel account. https://github.com/aschey/vercel-tokei

**Comment by XAMPPRocky** [comment] 2023-07-17 08:05
> Since it's serverless, it'll just spin up a new container if the current one dies. 

To be clear, as I mentioned above, the problem is not the service "dying", it's that the server runs out of storage space from large repositories. I'd warn anyone against using a service like Vercel to host the service publicly because they offer extremely small amounts of storage for prices that are more double what it costs to run on a VPS with 80x the storage capacity. And since there's no storage space check currently, you run the risk of having a runaway bill from someone requesting the statistics of LLVM.

**Comment by XAMPPRocky** [comment] 2024-03-17 21:27
I've moved to some new infra, which should prevent this from happening again, so going to close for now.

**Closed by XAMPPRocky** 2024-03-17 21:27 UTC

**Comment by Trolldemorted** [comment] 2024-06-08 14:42
It's down again :(

**Comment by ISSOtm** [comment] 2024-08-06 19:33
Cloudflare is currently returning a `525`. I don't know if this is related.

(By the way, I almost missed that this issue existed. Might I suggest pinning it and/or renaming it, to increase its visibility? And thank you for your efforts! ^^)
